// ─────────────────────────────────────────────────────────────
// GENERATED by tools/gen-tiles.fsx — DO NOT EDIT BY HAND.
// Regenerate with:  dotnet fsi tools/gen-tiles.fsx
// Sources: assets/kenney_tower-defense-top-down/towerDefense_tilesheet.xml,
//          assets/kenney_top-down-tanks-remastered/allSprites_default.xml
// ─────────────────────────────────────────────────────────────
namespace Defli.World

open System.Collections.Frozen
open System.Collections.Generic

module Tiles =

  [<Literal>]
  let SheetPath = "kenney_tower-defense-top-down/towerDefense_tilesheet.png"

  [<Literal>]
  let TileSize = 64

  /// All 299 atlas tiles (name, position, size) baked at compile time.
  /// Canonical store: ordered and iterable. The name index is built from it.
  let all: TileInfo[] = [|
    {
      Name = "grass_patch_on_dirt_top_left"
      X = 0
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_dirt_top"
      X = 64
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_dirt_top_right"
      X = 128
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_grass_top_left"
      X = 192
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_grass_top_right"
      X = 256
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_top_left"
      X = 320
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_top"
      X = 384
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_top_right"
      X = 448
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_sand_top_left"
      X = 512
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_sand_top_right"
      X = 576
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_top_left"
      X = 640
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_top"
      X = 704
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_top_right"
      X = 768
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_stone_top_left"
      X = 832
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_stone_top_right"
      X = 896
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "button_white"
      X = 960
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "button_white_wrench"
      X = 1024
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "button_white_close"
      X = 1088
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "button_white_target"
      X = 1152
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "effect_impact_ring"
      X = 1216
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "effect_impact_debris"
      X = 1280
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "effect_impact_burst"
      X = 1344
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "crosshair"
      X = 1408
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_dirt_left"
      X = 0
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_dirt_center"
      X = 64
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_dirt_right"
      X = 128
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_grass_bottom_left"
      X = 192
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_grass_bottom_right"
      X = 256
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_left"
      X = 320
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_center"
      X = 384
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_right"
      X = 448
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_sand_bottom_left"
      X = 512
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_sand_bottom_right"
      X = 576
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_left"
      X = 640
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_center"
      X = 704
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_right"
      X = 768
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_stone_bottom_left"
      X = 832
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_circle_on_stone_bottom_right"
      X = 896
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "button_green"
      X = 960
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "button_green_wrench"
      X = 1024
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "button_green_close"
      X = 1088
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "button_green_target"
      X = 1152
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "button_green_alt"
      X = 1216
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "button_green_wrench_alt"
      X = 1280
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "button_green_close_alt"
      X = 1344
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "button_green_target_alt"
      X = 1408
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_dirt_bottom_left"
      X = 0
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_dirt_bottom"
      X = 64
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_dirt_bottom_right"
      X = 128
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "grass_dot_on_dirt"
      X = 192
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_full_a"
      X = 256
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_bottom_left"
      X = 320
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_bottom"
      X = 384
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_dirt_bottom_right"
      X = 448
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "sand_dot_on_dirt"
      X = 512
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_full_b"
      X = 576
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_bottom_left"
      X = 640
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_bottom"
      X = 704
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_dirt_bottom_right"
      X = 768
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "stone_dot_on_dirt"
      X = 832
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_full_c"
      X = 896
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "button_brown"
      X = 960
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "button_brown_wrench"
      X = 1024
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "button_brown_close"
      X = 1088
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "button_brown_target"
      X = 1152
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "button_brown_alt"
      X = 1216
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "button_brown_wrench_alt"
      X = 1280
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "button_brown_close_alt"
      X = 1344
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "button_brown_target_alt"
      X = 1408
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_top_left"
      X = 0
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_top"
      X = 64
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_top_right"
      X = 128
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_dirt_top_left"
      X = 192
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_dirt_top_right"
      X = 256
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_top_left"
      X = 320
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_top"
      X = 384
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_top_right"
      X = 448
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_sand_top_left"
      X = 512
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_sand_top_right"
      X = 576
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_top_left"
      X = 640
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_top"
      X = 704
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_top_right"
      X = 768
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_stone_top_left"
      X = 832
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_stone_top_right"
      X = 896
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "button_steel"
      X = 960
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "button_steel_wrench"
      X = 1024
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "button_steel_close"
      X = 1088
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "button_steel_target"
      X = 1152
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "button_steel_alt"
      X = 1216
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "button_steel_wrench_alt"
      X = 1280
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "button_steel_close_alt"
      X = 1344
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "button_steel_target_alt"
      X = 1408
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_left"
      X = 0
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_center"
      X = 64
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_right"
      X = 128
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_dirt_bottom_left"
      X = 192
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_dirt_bottom_right"
      X = 256
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_left"
      X = 320
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_center"
      X = 384
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_right"
      X = 448
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_sand_bottom_left"
      X = 512
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_sand_bottom_right"
      X = 576
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_left"
      X = 640
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_center"
      X = 704
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_right"
      X = 768
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_stone_bottom_left"
      X = 832
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "grass_circle_on_stone_bottom_right"
      X = 896
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "button_beige"
      X = 960
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "button_beige_wrench"
      X = 1024
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "button_beige_close"
      X = 1088
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "button_beige_target"
      X = 1152
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "button_beige_alt"
      X = 1216
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "button_beige_wrench_alt"
      X = 1280
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "button_beige_close_alt"
      X = 1344
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "button_beige_target_alt"
      X = 1408
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_bottom_left"
      X = 0
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_bottom"
      X = 64
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_grass_bottom_right"
      X = 128
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_dot_on_grass"
      X = 192
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "grass_full_a"
      X = 256
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_bottom_left"
      X = 320
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_bottom"
      X = 384
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_grass_bottom_right"
      X = 448
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "sand_dot_on_grass"
      X = 512
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "grass_full_b"
      X = 576
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_bottom_left"
      X = 640
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_bottom"
      X = 704
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_grass_bottom_right"
      X = 768
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "stone_dot_on_grass"
      X = 832
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "grass_full_c"
      X = 896
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "tree_large"
      X = 960
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "bush_small"
      X = 1024
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "plant_sprig"
      X = 1088
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "tree_round"
      X = 1152
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "tree_pine"
      X = 1216
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "rock_small"
      X = 1280
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "rock_large"
      X = 1344
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "rock_medium"
      X = 1408
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_top_left"
      X = 0
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_top"
      X = 64
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_top_right"
      X = 128
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_grass_top_left"
      X = 192
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_grass_top_right"
      X = 256
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_top_left"
      X = 320
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_top"
      X = 384
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_top_right"
      X = 448
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_dirt_top_left"
      X = 512
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_dirt_top_right"
      X = 576
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_top_left"
      X = 640
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_top"
      X = 704
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_top_right"
      X = 768
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_stone_top_left"
      X = 832
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_stone_top_right"
      X = 896
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "path_end_up_grass"
      X = 960
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "path_end_up_dirt"
      X = 1024
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "path_end_up_stone"
      X = 1088
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "path_end_up_sand"
      X = 1152
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "grass_full_textured"
      X = 1216
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_full_textured"
      X = 1280
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "stone_full_textured"
      X = 1344
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "sand_full_textured"
      X = 1408
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_left"
      X = 0
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_center"
      X = 64
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_right"
      X = 128
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_grass_bottom_left"
      X = 192
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_grass_bottom_right"
      X = 256
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_left"
      X = 320
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_center"
      X = 384
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_right"
      X = 448
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_dirt_bottom_left"
      X = 512
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_dirt_bottom_right"
      X = 576
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_left"
      X = 640
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_center"
      X = 704
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_right"
      X = 768
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_stone_bottom_left"
      X = 832
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "sand_circle_on_stone_bottom_right"
      X = 896
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "path_vertical_grass"
      X = 960
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "path_vertical_dirt"
      X = 1024
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "path_vertical_stone"
      X = 1088
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "path_vertical_sand"
      X = 1152
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "crate_metal_square"
      X = 1216
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "crate_metal_octagon"
      X = 1280
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "crate_metal_beveled"
      X = 1344
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "crate_metal_diamond"
      X = 1408
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_bottom_left"
      X = 0
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_bottom"
      X = 64
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_sand_bottom_right"
      X = 128
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "grass_dot_on_sand"
      X = 192
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "sand_full_a"
      X = 256
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_bottom_left"
      X = 320
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_bottom"
      X = 384
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_sand_bottom_right"
      X = 448
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_dot_on_sand"
      X = 512
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "sand_full_b"
      X = 576
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_bottom_left"
      X = 640
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_bottom"
      X = 704
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "stone_patch_on_sand_bottom_right"
      X = 768
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "stone_dot_on_sand"
      X = 832
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "sand_full_c"
      X = 896
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "path_end_left_grass"
      X = 960
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "path_end_left_dirt"
      X = 1024
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "path_end_left_stone"
      X = 1088
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "path_end_left_sand"
      X = 1152
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "turret_mount_empty"
      X = 1216
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "turret_missiles_dual"
      X = 1280
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "rocket_pod_dual"
      X = 1344
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "rocket_pod_single"
      X = 1408
      Y = 512
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_top_left"
      X = 0
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_top"
      X = 64
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_top_right"
      X = 128
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_grass_top_left"
      X = 192
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_grass_top_right"
      X = 256
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_top_left"
      X = 320
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_top"
      X = 384
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_top_right"
      X = 448
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_dirt_top_left"
      X = 512
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_dirt_top_right"
      X = 576
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_top_left"
      X = 640
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_top"
      X = 704
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_top_right"
      X = 768
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_sand_top_left"
      X = 832
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_sand_top_right"
      X = 896
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "path_horizontal_grass"
      X = 960
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "path_horizontal_dirt"
      X = 1024
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "path_horizontal_stone"
      X = 1088
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "path_horizontal_sand"
      X = 1152
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "turret_base_a"
      X = 1216
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "turret_base_b"
      X = 1280
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "container_large"
      X = 1344
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "container_small"
      X = 1408
      Y = 576
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_left"
      X = 0
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_center"
      X = 64
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_right"
      X = 128
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_grass_bottom_left"
      X = 192
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_grass_bottom_right"
      X = 256
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_left"
      X = 320
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_center"
      X = 384
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_right"
      X = 448
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_dirt_bottom_left"
      X = 512
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_dirt_bottom_right"
      X = 576
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_left"
      X = 640
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_center"
      X = 704
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_right"
      X = 768
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_sand_bottom_left"
      X = 832
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "stone_circle_on_sand_bottom_right"
      X = 896
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "tank_green"
      X = 960
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "tank_slate"
      X = 1024
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "tank_brown"
      X = 1088
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "tank_gray"
      X = 1152
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "turret_green"
      X = 1216
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "turret_red_dual"
      X = 1280
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "rocket_small"
      X = 1344
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "rocket_large"
      X = 1408
      Y = 640
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_bottom_left"
      X = 0
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_bottom"
      X = 64
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "grass_patch_on_stone_bottom_right"
      X = 128
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "grass_dot_on_stone"
      X = 192
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "stone_full_a"
      X = 256
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_bottom_left"
      X = 320
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_bottom"
      X = 384
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_patch_on_stone_bottom_right"
      X = 448
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "dirt_dot_on_stone"
      X = 512
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "stone_full_b"
      X = 576
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_bottom_left"
      X = 640
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_bottom"
      X = 704
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "sand_patch_on_stone_bottom_right"
      X = 768
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "sand_dot_on_stone"
      X = 832
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "stone_full_c"
      X = 896
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "crate_green"
      X = 960
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "crate_beige"
      X = 1024
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "plane_green"
      X = 1088
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "plane_gray"
      X = 1152
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "coin_gold"
      X = 1216
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "coin_gold_rimmed"
      X = 1280
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "coin_copper"
      X = 1344
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "coin_silver"
      X = 1408
      Y = 704
      Width = 64
      Height = 64
    }
    {
      Name = "digit_0"
      X = 0
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_1"
      X = 64
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_2"
      X = 128
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_3"
      X = 192
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_4"
      X = 256
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_5"
      X = 320
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_6"
      X = 384
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_7"
      X = 448
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_8"
      X = 512
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "digit_9"
      X = 576
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "symbol_percent"
      X = 640
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "symbol_dollar"
      X = 704
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "symbol_colon"
      X = 768
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "symbol_plus"
      X = 832
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "symbol_period"
      X = 896
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "tank_turret_green"
      X = 960
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "tank_turret_beige"
      X = 1024
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "plane_ghost_a"
      X = 1088
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "plane_ghost_b"
      X = 1152
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "flame_small"
      X = 1216
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "flame_large"
      X = 1280
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "flame_thin"
      X = 1344
      Y = 768
      Width = 64
      Height = 64
    }
    {
      Name = "flame_spread"
      X = 1408
      Y = 768
      Width = 64
      Height = 64
    }
  |]

  /// O(1) name index over the baked dataset (built once at module init).
  let byName: FrozenDictionary<string, TileInfo> =
    all
    |> Seq.map(fun t -> KeyValuePair(t.Name, t))
    |> FrozenDictionary.ToFrozenDictionary

  /// Safe name lookup for data-driven code (tower/enemy defs, procedural gen).
  let tryByName(name: string) : TileInfo voption =
    Defli.FrozenDict.tryGetValue name byName

  // ── Semantically named tiles (curated in the generator) ──
  /// grass_full_a — atlas position (256, 320), 64x64.
  let grassFullA = byName["grass_full_a"]
  /// grass_full_b — atlas position (576, 320), 64x64.
  let grassFullB = byName["grass_full_b"]
  /// grass_full_c — atlas position (896, 320), 64x64.
  let grassFullC = byName["grass_full_c"]
  /// dirt_full_a — atlas position (256, 128), 64x64.
  let dirtFullA = byName["dirt_full_a"]
  /// dirt_full_b — atlas position (576, 128), 64x64.
  let dirtFullB = byName["dirt_full_b"]
  /// dirt_full_c — atlas position (896, 128), 64x64.
  let dirtFullC = byName["dirt_full_c"]
  /// path_vertical_dirt — atlas position (1024, 448), 64x64.
  let pathVerticalDirt = byName["path_vertical_dirt"]
  /// path_horizontal_dirt — atlas position (1024, 576), 64x64.
  let pathHorizontalDirt = byName["path_horizontal_dirt"]
  /// path_end_up_dirt — atlas position (1024, 384), 64x64.
  let pathEndUpDirt = byName["path_end_up_dirt"]
  /// path_end_left_dirt — atlas position (1024, 512), 64x64.
  let pathEndLeftDirt = byName["path_end_left_dirt"]
  /// turret_mount_empty — atlas position (1216, 512), 64x64.
  let turretMountEmpty = byName["turret_mount_empty"]
  /// turret_base_a — atlas position (1216, 576), 64x64.
  let turretBaseA = byName["turret_base_a"]
  /// turret_green — atlas position (1216, 640), 64x64.
  let turretGreen = byName["turret_green"]
  /// rocket_pod_single — atlas position (1408, 512), 64x64.
  let rocketPodSingle = byName["rocket_pod_single"]
  /// rocket_pod_dual — atlas position (1344, 512), 64x64.
  let rocketPodDual = byName["rocket_pod_dual"]
  /// rocket_small — atlas position (1344, 640), 64x64.
  let rocketSmall = byName["rocket_small"]
  /// coin_gold — atlas position (1216, 704), 64x64.
  let coinGold = byName["coin_gold"]
  /// effect_impact_burst — atlas position (1344, 0), 64x64.
  let effectImpactBurst = byName["effect_impact_burst"]
  /// effect_impact_ring — atlas position (1216, 0), 64x64.
  let effectImpactRing = byName["effect_impact_ring"]
  /// effect_impact_debris — atlas position (1280, 0), 64x64.
  let effectImpactDebris = byName["effect_impact_debris"]
  /// crosshair — atlas position (1408, 0), 64x64.
  let crosshair = byName["crosshair"]

  // ── Groups (curated in the generator) ──
  let groundGrass = [| grassFullA; grassFullB; grassFullC |]
  let groundDirt = [| dirtFullA; dirtFullB; dirtFullC |]

  let pathDirt = [|
    pathVerticalDirt
    pathHorizontalDirt
    pathEndUpDirt
    pathEndLeftDirt
  |]

  let effects = [| effectImpactBurst; effectImpactRing; effectImpactDebris |]

module Tanks =

  [<Literal>]
  let SheetPath = "kenney_top-down-tanks-remastered/allSprites_default.png"

  /// All 187 atlas tiles (name, position, size) baked at compile time.
  /// Canonical store: ordered and iterable. The name index is built from it.
  let all: TileInfo[] = [|
    {
      Name = "barrelBlack_side"
      X = 513
      Y = 407
      Width = 20
      Height = 28
    }
    {
      Name = "barrelBlack_top"
      X = 507
      Y = 515
      Width = 24
      Height = 24
    }
    {
      Name = "barrelGreen_side"
      X = 513
      Y = 319
      Width = 20
      Height = 28
    }
    {
      Name = "barrelGreen_top"
      X = 507
      Y = 443
      Width = 24
      Height = 24
    }
    {
      Name = "barrelRed_side"
      X = 414
      Y = 371
      Width = 20
      Height = 28
    }
    {
      Name = "barrelRed_top"
      X = 507
      Y = 491
      Width = 24
      Height = 24
    }
    {
      Name = "barrelRust_side"
      X = 512
      Y = 40
      Width = 20
      Height = 28
    }
    {
      Name = "barrelRust_top"
      X = 507
      Y = 467
      Width = 24
      Height = 24
    }
    {
      Name = "barricadeMetal"
      X = 479
      Y = 499
      Width = 28
      Height = 28
    }
    {
      Name = "barricadeWood"
      X = 479
      Y = 527
      Width = 28
      Height = 28
    }
    {
      Name = "bulletBlue1"
      X = 356
      Y = 555
      Width = 4
      Height = 10
    }
    {
      Name = "bulletBlue1_outline"
      X = 544
      Y = 26
      Width = 8
      Height = 14
    }
    {
      Name = "bulletBlue2"
      X = 532
      Y = 48
      Width = 8
      Height = 12
    }
    {
      Name = "bulletBlue2_outline"
      X = 438
      Y = 455
      Width = 12
      Height = 16
    }
    {
      Name = "bulletBlue3"
      X = 500
      Y = 130
      Width = 4
      Height = 14
    }
    {
      Name = "bulletBlue3_outline"
      X = 513
      Y = 202
      Width = 8
      Height = 18
    }
    {
      Name = "bulletDark1"
      X = 386
      Y = 393
      Width = 4
      Height = 10
    }
    {
      Name = "bulletDark1_outline"
      X = 462
      Y = 455
      Width = 8
      Height = 14
    }
    {
      Name = "bulletDark2"
      X = 470
      Y = 455
      Width = 8
      Height = 12
    }
    {
      Name = "bulletDark2_outline"
      X = 196
      Y = 544
      Width = 12
      Height = 16
    }
    {
      Name = "bulletDark3"
      X = 435
      Y = 231
      Width = 4
      Height = 14
    }
    {
      Name = "bulletDark3_outline"
      X = 531
      Y = 517
      Width = 8
      Height = 18
    }
    {
      Name = "bulletGreen1"
      X = 435
      Y = 245
      Width = 4
      Height = 10
    }
    {
      Name = "bulletGreen1_outline"
      X = 532
      Y = 160
      Width = 8
      Height = 14
    }
    {
      Name = "bulletGreen2"
      X = 521
      Y = 202
      Width = 8
      Height = 12
    }
    {
      Name = "bulletGreen2_outline"
      X = 172
      Y = 544
      Width = 12
      Height = 16
    }
    {
      Name = "bulletGreen3"
      X = 471
      Y = 283
      Width = 4
      Height = 14
    }
    {
      Name = "bulletGreen3_outline"
      X = 492
      Y = 130
      Width = 8
      Height = 18
    }
    {
      Name = "bulletRed1"
      X = 382
      Y = 393
      Width = 4
      Height = 10
    }
    {
      Name = "bulletRed1_outline"
      X = 344
      Y = 551
      Width = 8
      Height = 14
    }
    {
      Name = "bulletRed2"
      X = 336
      Y = 551
      Width = 8
      Height = 12
    }
    {
      Name = "bulletRed2_outline"
      X = 184
      Y = 544
      Width = 12
      Height = 16
    }
    {
      Name = "bulletRed3"
      X = 206
      Y = 528
      Width = 4
      Height = 14
    }
    {
      Name = "bulletRed3_outline"
      X = 484
      Y = 130
      Width = 8
      Height = 18
    }
    {
      Name = "bulletSand1"
      X = 352
      Y = 555
      Width = 4
      Height = 10
    }
    {
      Name = "bulletSand1_outline"
      X = 320
      Y = 551
      Width = 8
      Height = 14
    }
    {
      Name = "bulletSand2"
      X = 312
      Y = 551
      Width = 8
      Height = 12
    }
    {
      Name = "bulletSand2_outline"
      X = 450
      Y = 455
      Width = 12
      Height = 16
    }
    {
      Name = "bulletSand3"
      X = 471
      Y = 297
      Width = 4
      Height = 14
    }
    {
      Name = "bulletSand3_outline"
      X = 476
      Y = 130
      Width = 8
      Height = 18
    }
    {
      Name = "crateMetal"
      X = 479
      Y = 471
      Width = 28
      Height = 28
    }
    {
      Name = "crateMetal_side"
      X = 479
      Y = 443
      Width = 28
      Height = 28
    }
    {
      Name = "crateWood"
      X = 480
      Y = 221
      Width = 28
      Height = 28
    }
    {
      Name = "crateWood_side"
      X = 480
      Y = 249
      Width = 28
      Height = 28
    }
    {
      Name = "explosion1"
      X = 320
      Y = 403
      Width = 60
      Height = 60
    }
    {
      Name = "explosion2"
      X = 380
      Y = 471
      Width = 57
      Height = 56
    }
    {
      Name = "explosion3"
      X = 0
      Y = 128
      Width = 64
      Height = 63
    }
    {
      Name = "explosion4"
      X = 430
      Y = 104
      Width = 46
      Height = 45
    }
    {
      Name = "explosion5"
      X = 53
      Y = 512
      Width = 53
      Height = 52
    }
    {
      Name = "explosionSmoke1"
      X = 320
      Y = 463
      Width = 60
      Height = 60
    }
    {
      Name = "explosionSmoke2"
      X = 382
      Y = 255
      Width = 57
      Height = 56
    }
    {
      Name = "explosionSmoke3"
      X = 320
      Y = 192
      Width = 63
      Height = 63
    }
    {
      Name = "explosionSmoke4"
      X = 384
      Y = 104
      Width = 46
      Height = 45
    }
    {
      Name = "explosionSmoke5"
      X = 0
      Y = 512
      Width = 53
      Height = 52
    }
    {
      Name = "fenceRed"
      X = 158
      Y = 528
      Width = 48
      Height = 16
    }
    {
      Name = "fenceYellow"
      X = 158
      Y = 512
      Width = 52
      Height = 16
    }
    {
      Name = "oilSpill_large"
      X = 262
      Y = 512
      Width = 50
      Height = 50
    }
    {
      Name = "oilSpill_small"
      X = 158
      Y = 544
      Width = 14
      Height = 14
    }
    {
      Name = "sandbagBeige"
      X = 382
      Y = 371
      Width = 32
      Height = 22
    }
    {
      Name = "sandbagBeige_open"
      X = 354
      Y = 527
      Width = 42
      Height = 28
    }
    {
      Name = "sandbagBrown"
      X = 439
      Y = 283
      Width = 32
      Height = 22
    }
    {
      Name = "sandbagBrown_open"
      X = 312
      Y = 523
      Width = 42
      Height = 28
    }
    {
      Name = "shotLarge"
      X = 507
      Y = 539
      Width = 20
      Height = 25
    }
    {
      Name = "shotOrange"
      X = 514
      Y = 289
      Width = 16
      Height = 28
    }
    {
      Name = "shotRed"
      X = 508
      Y = 221
      Width = 21
      Height = 38
    }
    {
      Name = "shotThin"
      X = 546
      Y = 160
      Width = 8
      Height = 26
    }
    {
      Name = "specialBarrel1"
      X = 530
      Y = 0
      Width = 14
      Height = 22
    }
    {
      Name = "specialBarrel1_outline"
      X = 527
      Y = 539
      Width = 18
      Height = 26
    }
    {
      Name = "specialBarrel2"
      X = 544
      Y = 108
      Width = 12
      Height = 24
    }
    {
      Name = "specialBarrel2_outline"
      X = 513
      Y = 174
      Width = 16
      Height = 28
    }
    {
      Name = "specialBarrel3"
      X = 544
      Y = 132
      Width = 10
      Height = 28
    }
    {
      Name = "specialBarrel3_outline"
      X = 530
      Y = 244
      Width = 14
      Height = 32
    }
    {
      Name = "specialBarrel4"
      X = 544
      Y = 244
      Width = 10
      Height = 32
    }
    {
      Name = "specialBarrel4_outline"
      X = 530
      Y = 276
      Width = 14
      Height = 36
    }
    {
      Name = "specialBarrel5"
      X = 531
      Y = 435
      Width = 12
      Height = 26
    }
    {
      Name = "specialBarrel5_outline"
      X = 514
      Y = 98
      Width = 16
      Height = 30
    }
    {
      Name = "specialBarrel6"
      X = 544
      Y = 276
      Width = 8
      Height = 26
    }
    {
      Name = "specialBarrel6_outline"
      X = 533
      Y = 312
      Width = 12
      Height = 30
    }
    {
      Name = "specialBarrel7"
      X = 544
      Y = 0
      Width = 8
      Height = 26
    }
    {
      Name = "specialBarrel7_outline"
      X = 530
      Y = 68
      Width = 12
      Height = 30
    }
    {
      Name = "tankBlue_barrel1"
      X = 531
      Y = 461
      Width = 12
      Height = 26
    }
    {
      Name = "tankBlue_barrel1_outline"
      X = 514
      Y = 259
      Width = 16
      Height = 30
    }
    {
      Name = "tankBlue_barrel2"
      X = 545
      Y = 302
      Width = 8
      Height = 26
    }
    {
      Name = "tankBlue_barrel2_outline"
      X = 542
      Y = 48
      Width = 12
      Height = 30
    }
    {
      Name = "tankBlue_barrel3"
      X = 545
      Y = 519
      Width = 8
      Height = 26
    }
    {
      Name = "tankBlue_barrel3_outline"
      X = 543
      Y = 459
      Width = 12
      Height = 30
    }
    {
      Name = "tankBody_bigRed"
      X = 384
      Y = 56
      Width = 48
      Height = 48
    }
    {
      Name = "tankBody_bigRed_outline"
      X = 106
      Y = 512
      Width = 52
      Height = 52
    }
    {
      Name = "tankBody_blue"
      X = 396
      Y = 527
      Width = 38
      Height = 38
    }
    {
      Name = "tankBody_blue_outline"
      X = 426
      Y = 149
      Width = 42
      Height = 42
    }
    {
      Name = "tankBody_dark"
      X = 468
      Y = 149
      Width = 38
      Height = 36
    }
    {
      Name = "tankBody_darkLarge"
      X = 384
      Y = 0
      Width = 48
      Height = 56
    }
    {
      Name = "tankBody_darkLarge_outline"
      X = 382
      Y = 311
      Width = 52
      Height = 60
    }
    {
      Name = "tankBody_dark_outline"
      X = 384
      Y = 149
      Width = 42
      Height = 40
    }
    {
      Name = "tankBody_green"
      X = 476
      Y = 283
      Width = 38
      Height = 36
    }
    {
      Name = "tankBody_green_outline"
      X = 435
      Y = 191
      Width = 42
      Height = 40
    }
    {
      Name = "tankBody_huge"
      X = 380
      Y = 403
      Width = 58
      Height = 68
    }
    {
      Name = "tankBody_huge_outline"
      X = 320
      Y = 331
      Width = 62
      Height = 72
    }
    {
      Name = "tankBody_red"
      X = 479
      Y = 407
      Width = 34
      Height = 36
    }
    {
      Name = "tankBody_red_outline"
      X = 476
      Y = 0
      Width = 38
      Height = 40
    }
    {
      Name = "tankBody_sand"
      X = 476
      Y = 94
      Width = 38
      Height = 36
    }
    {
      Name = "tankBody_sand_outline"
      X = 437
      Y = 517
      Width = 42
      Height = 40
    }
    {
      Name = "tankDark_barrel1"
      X = 543
      Y = 342
      Width = 12
      Height = 26
    }
    {
      Name = "tankDark_barrel1_outline"
      X = 514
      Y = 68
      Width = 16
      Height = 30
    }
    {
      Name = "tankDark_barrel2"
      X = 545
      Y = 398
      Width = 8
      Height = 26
    }
    {
      Name = "tankDark_barrel2_outline"
      X = 531
      Y = 373
      Width = 12
      Height = 30
    }
    {
      Name = "tankDark_barrel3"
      X = 553
      Y = 519
      Width = 8
      Height = 26
    }
    {
      Name = "tankDark_barrel3_outline"
      X = 543
      Y = 429
      Width = 12
      Height = 30
    }
    {
      Name = "tankGreen_barrel1"
      X = 533
      Y = 403
      Width = 12
      Height = 26
    }
    {
      Name = "tankGreen_barrel1_outline"
      X = 515
      Y = 377
      Width = 16
      Height = 30
    }
    {
      Name = "tankGreen_barrel2"
      X = 553
      Y = 398
      Width = 8
      Height = 26
    }
    {
      Name = "tankGreen_barrel2_outline"
      X = 530
      Y = 98
      Width = 12
      Height = 30
    }
    {
      Name = "tankGreen_barrel3"
      X = 552
      Y = 276
      Width = 8
      Height = 26
    }
    {
      Name = "tankGreen_barrel3_outline"
      X = 531
      Y = 487
      Width = 12
      Height = 30
    }
    {
      Name = "tankRed_barrel1"
      X = 531
      Y = 347
      Width = 12
      Height = 26
    }
    {
      Name = "tankRed_barrel1_outline"
      X = 514
      Y = 0
      Width = 16
      Height = 30
    }
    {
      Name = "tankRed_barrel2"
      X = 546
      Y = 212
      Width = 8
      Height = 26
    }
    {
      Name = "tankRed_barrel2_outline"
      X = 543
      Y = 368
      Width = 12
      Height = 30
    }
    {
      Name = "tankRed_barrel3"
      X = 553
      Y = 302
      Width = 8
      Height = 26
    }
    {
      Name = "tankRed_barrel3_outline"
      X = 532
      Y = 128
      Width = 12
      Height = 30
    }
    {
      Name = "tankSand_barrel1"
      X = 532
      Y = 22
      Width = 12
      Height = 26
    }
    {
      Name = "tankSand_barrel1_outline"
      X = 515
      Y = 347
      Width = 16
      Height = 30
    }
    {
      Name = "tankSand_barrel2"
      X = 546
      Y = 186
      Width = 8
      Height = 26
    }
    {
      Name = "tankSand_barrel2_outline"
      X = 542
      Y = 78
      Width = 12
      Height = 30
    }
    {
      Name = "tankSand_barrel3"
      X = 552
      Y = 0
      Width = 8
      Height = 26
    }
    {
      Name = "tankSand_barrel3_outline"
      X = 543
      Y = 489
      Width = 12
      Height = 30
    }
    {
      Name = "tank_bigRed"
      X = 210
      Y = 512
      Width = 52
      Height = 52
    }
    {
      Name = "tank_blue"
      X = 432
      Y = 48
      Width = 42
      Height = 46
    }
    {
      Name = "tank_dark"
      X = 434
      Y = 311
      Width = 42
      Height = 46
    }
    {
      Name = "tank_darkLarge"
      X = 383
      Y = 192
      Width = 52
      Height = 60
    }
    {
      Name = "tank_green"
      X = 434
      Y = 357
      Width = 42
      Height = 46
    }
    {
      Name = "tank_huge"
      X = 320
      Y = 255
      Width = 62
      Height = 76
    }
    {
      Name = "tank_red"
      X = 474
      Y = 48
      Width = 38
      Height = 46
    }
    {
      Name = "tank_sand"
      X = 437
      Y = 471
      Width = 42
      Height = 46
    }
    {
      Name = "tileGrass1"
      X = 192
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "tileGrass2"
      X = 192
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "tileGrass_roadCornerLL"
      X = 64
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "tileGrass_roadCornerLR"
      X = 64
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "tileGrass_roadCornerUL"
      X = 0
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "tileGrass_roadCornerUR"
      X = 192
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "tileGrass_roadCrossing"
      X = 0
      Y = 319
      Width = 64
      Height = 64
    }
    {
      Name = "tileGrass_roadCrossingRound"
      X = 64
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "tileGrass_roadEast"
      X = 64
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "tileGrass_roadNorth"
      X = 192
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "tileGrass_roadSplitE"
      X = 192
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "tileGrass_roadSplitN"
      X = 192
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "tileGrass_roadSplitS"
      X = 64
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "tileGrass_roadSplitW"
      X = 64
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "tileGrass_roadTransitionE"
      X = 192
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "tileGrass_roadTransitionE_dirt"
      X = 320
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "tileGrass_roadTransitionN"
      X = 320
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "tileGrass_roadTransitionN_dirt"
      X = 256
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "tileGrass_roadTransitionS"
      X = 256
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "tileGrass_roadTransitionS_dirt"
      X = 256
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "tileGrass_roadTransitionW"
      X = 256
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "tileGrass_roadTransitionW_dirt"
      X = 256
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "tileGrass_transitionE"
      X = 256
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "tileGrass_transitionN"
      X = 256
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "tileGrass_transitionS"
      X = 256
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "tileGrass_transitionW"
      X = 192
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "tileSand1"
      X = 128
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "tileSand2"
      X = 64
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "tileSand_roadCornerLL"
      X = 0
      Y = 255
      Width = 64
      Height = 64
    }
    {
      Name = "tileSand_roadCornerLR"
      X = 0
      Y = 191
      Width = 64
      Height = 64
    }
    {
      Name = "tileSand_roadCornerUL"
      X = 0
      Y = 0
      Width = 64
      Height = 64
    }
    {
      Name = "tileSand_roadCornerUR"
      X = 0
      Y = 383
      Width = 64
      Height = 64
    }
    {
      Name = "tileSand_roadCrossing"
      X = 320
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "tileSand_roadCrossingRound"
      X = 128
      Y = 448
      Width = 64
      Height = 64
    }
    {
      Name = "tileSand_roadEast"
      X = 128
      Y = 384
      Width = 64
      Height = 64
    }
    {
      Name = "tileSand_roadNorth"
      X = 128
      Y = 320
      Width = 64
      Height = 64
    }
    {
      Name = "tileSand_roadSplitE"
      X = 128
      Y = 256
      Width = 64
      Height = 64
    }
    {
      Name = "tileSand_roadSplitN"
      X = 128
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "tileSand_roadSplitS"
      X = 128
      Y = 128
      Width = 64
      Height = 64
    }
    {
      Name = "tileSand_roadSplitW"
      X = 128
      Y = 64
      Width = 64
      Height = 64
    }
    {
      Name = "tracksDouble"
      X = 438
      Y = 403
      Width = 41
      Height = 52
    }
    {
      Name = "tracksLarge"
      X = 439
      Y = 231
      Width = 41
      Height = 52
    }
    {
      Name = "tracksSmall"
      X = 476
      Y = 319
      Width = 37
      Height = 52
    }
    {
      Name = "treeBrown_large"
      X = 64
      Y = 192
      Width = 64
      Height = 64
    }
    {
      Name = "treeBrown_leaf"
      X = 312
      Y = 512
      Width = 8
      Height = 10
    }
    {
      Name = "treeBrown_small"
      X = 479
      Y = 371
      Width = 36
      Height = 36
    }
    {
      Name = "treeBrown_twigs"
      X = 506
      Y = 130
      Width = 26
      Height = 22
    }
    {
      Name = "treeGreen_large"
      X = 0
      Y = 447
      Width = 64
      Height = 64
    }
    {
      Name = "treeGreen_leaf"
      X = 328
      Y = 555
      Width = 8
      Height = 10
    }
    {
      Name = "treeGreen_small"
      X = 477
      Y = 185
      Width = 36
      Height = 36
    }
    {
      Name = "treeGreen_twigs"
      X = 506
      Y = 152
      Width = 26
      Height = 22
    }
    {
      Name = "wireCrooked"
      X = 432
      Y = 0
      Width = 44
      Height = 48
    }
    {
      Name = "wireStraight"
      X = 529
      Y = 174
      Width = 17
      Height = 70
    }
  |]

  /// O(1) name index over the baked dataset (built once at module init).
  let byName: FrozenDictionary<string, TileInfo> =
    all
    |> Seq.map(fun t -> KeyValuePair(t.Name, t))
    |> FrozenDictionary.ToFrozenDictionary

  /// Safe name lookup for data-driven code (tower/enemy defs, procedural gen).
  let tryByName(name: string) : TileInfo voption =
    Defli.FrozenDict.tryGetValue name byName

  // ── Semantically named tiles (curated in the generator) ──
  /// tankBody_green — atlas position (476, 283), 38x36.
  let tankBodyGreen = byName["tankBody_green"]
  /// tankBody_blue — atlas position (396, 527), 38x38.
  let tankBodyBlue = byName["tankBody_blue"]
  /// tankBody_red — atlas position (479, 407), 34x36.
  let tankBodyRed = byName["tankBody_red"]
  /// tankBody_dark — atlas position (468, 149), 38x36.
  let tankBodyDark = byName["tankBody_dark"]
  /// tankBody_bigRed — atlas position (384, 56), 48x48.
  let tankBodyBigRed = byName["tankBody_bigRed"]
  /// tankBody_huge — atlas position (380, 403), 58x68.
  let tankBodyHuge = byName["tankBody_huge"]
  /// tankBody_darkLarge — atlas position (384, 0), 48x56.
  let tankBodyDarkLarge = byName["tankBody_darkLarge"]
  /// bulletRed1 — atlas position (382, 393), 4x10.
  let bulletRed1 = byName["bulletRed1"]

  // ── Groups (curated in the generator) ──
  let enemyBodies = [|
    tankBodyGreen
    tankBodyBlue
    tankBodyRed
    tankBodyDark
    tankBodyBigRed
    tankBodyHuge
    tankBodyDarkLarge
  |]
